In [ ]:
name = "Write your name here"
date_returned = "Write the date returned here"

# Lab 6. Matrices
Hardware 1 course - Mathematics<br>
Information and Communication Technology<br>
Metropolia University of Applied Sciences

## Setup

Read necessary libraries and functions.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import sin, cos, dot
from numpy.linalg import det, inv, solve

---
## Problem 1

Write your own code (e.g. do not use `numpy.linalg.inv`, but code yourself) to find the inverse of the following matrices:<br>
$A = \left( \begin{array}{cc} 2 & 3 \\ 4 & 1 \end{array} \right)$
and
$B = \left( \begin{array}{cc} 6 & 2 \\ 9 & 3 \end{array} \right)$

Then check with `numpy.linalg.inv()` your answers.

In [2]:
# My code to solve inverse of A


In [3]:
# Check with numpy.linalg.inv


array([[-0.1,  0.3],
       [ 0.4, -0.2]])

In [4]:
# My code to solve inverse of B


In [5]:
# Check with numpy.linalg.inv


array([[-3.00239975e+15,  2.00159983e+15],
       [ 9.00719925e+15, -6.00479950e+15]])

---
## Problem 2

If $A = \left( \begin{array}{cc} 1 & 3 \\ -2 & 4 \end{array} \right)$ and  $B = \left( \begin{array}{cc} 2 & 1 \\ -4 & 5 \end{array} \right)$, 

write your own code (e.g. do not use `numpy.dot` or `@` operator, but code yourself) to find $AB$ and $BA$.

Then, check with matrix multiplication operator `@`or with `numpy.dot()` your answers.

In [6]:
# My code to solve AB


array([[39, 13],
       [33, 11]])

In [ ]:
# Check with numpy.dot


In [ ]:
# My code to solve BA


In [ ]:
# Check with numpy.dot


---
## Problem 3

First, use paper and pen to find a generic algebraic solution for the linear equations for $x$ and $y$

\begin{align*} 
a_{11} x + a_{12}y &=  b_1 \\ 
a_{21} x + a_{22} y &= b_2
\end{align*}

Then, write a code (manually yourself, not using any ready linear algebra functions from numpy) that solves the following equations:

\begin{align*} 
2x - 5y &=  8 \\ 
3x + 9y &=  -12
\end{align*}

Finally, check your answer using `numpy.linalg.solve()`.

In [ ]:
# My code to solve the linear equations for x and y

# Print out the final result
print(f'x = {x}')
print(f'y = {y}')

In [ ]:
# Check with numpy.linalg.solve


---
## Problem 4
Solve the following equations using `numpy.linalg.solve()` 
\begin{align*}
2x + y + 3z = −1 \\
x − y − 2z = 5 \\
2x + y − 3z = 2
\end{align*}

In [ ]:
# Solution for problem 4


---
## Problem 5
Solve the following equations using numpy linear algebra operations
\begin{matrix} 
6x_1 + 6x_2 + 2x_3 + 3x_4 + 3x_5 = 7 \\
3x_1 + 8x_2 + 8x_3 + 6x_4 + 8x_5 = 4 \\
2x_1 + 3x_2 + 7x_3 + 6x_4 + 8x_5 = 1 \\
3x_1 + 8x_2 + 7x_3 + 2x_4 + 2x_5 = 2 \\
x_1 + 2x_2 + 8x_3 + 8x_4 + 8x_5 = 2
\end{matrix}

In [5]:
# Solution for problem 6



---
## Problem 6
Using numpy, determine if the following system has a nontrivial solution
\begin{align*}
2x − 3y − 2z = 0 \\
3x + y − 3z = 0 \\
x − 7y − z = 0 \\
\end{align*}

Note: nontrivial means that all $ x \neq 0$, $y \neq 0$, and $z \neq 0$. 

In [ ]:
# Solution for problem 5


---
## Problem 7
If $a_n = n^2$ (e.g. $a_1 = 1$, $a_2 = 2^2$, etc.) find the determinant of the cyclic matrix
$A = \left( \begin{matrix} 
a_1 & a_2 & a_3 & a_4 & a_5 \\
a_5 & a_1 & a_2 & a_3 & a_4 \\
a_4 & a_5 & a_1 & a_2 & a_3 \\
a_3 & a_4 & a_5 & a_1 & a_2 \\
a_2 & a_3 & a_4 & a_5 & a_1 \\
\end{matrix} \right)$

In [ ]:
# Solution for problem 7


---
## Problem 8
Find the determinant of the matrix 
$A = \left( \begin{matrix} 
1 & sin(3t) & sin^3(t) \\
2cos(t) & sin(6t) & sin^3(2t) \\
4cos^2(t) - 1 & sin(9t) & sin^3(3t)
\end{matrix} \right)$, when  

(a) $t = 1.0$, <br>
(b) $t = 2.03$, and <br>
(c) $t = -0.345$. <br>
Round the results to 3 decimals. What do you observe?

In [ ]:
# Solution (a)
np.sin(3*t)

In [ ]:
# Solution (c)


**My observations:**

---
## Problem 9
If $ A(a, x) = \left( \begin{matrix}
a + x & a - x & a - x \\
a - x & a + x & a - x \\
a - x & a - x & a + x
\end{matrix} \right)$ and $a = 1$, find $x > 0$, so that $det(A(a, x)) = 0$. 

How $a$ and $x$ are related? 

When you have found the relationship, try another value for $a$, for example $a = 2$.

Tip: Make a code that 
- uses linearly spaced values for $x \in [0, 10]$, for example. Use `numpy.linspace`.
- calculates the $f(x) = det(A(a, x))$ for all values of $x$ and then 
- makes a graphical plot of $f(x)$ versus $x$. 
- Finally, from the graph, find when $f(x) = 0$.

In [6]:
# Solution for problem 8


**The relationship between $a$ and $x$: (Write here your findings)**

---
## Problem 10
if $A = \left( \begin{matrix}
0 & 1 & 2 \\
1 & 2 & 3 \\
3 & a & 1 \end{matrix} \right)$ and 
$A^{-1} = \left( \begin{matrix}
0.5 & -0.5 & 0.5 \\
-4 & 3 & c \\
2.5 & -1.5 & 0.5 \end{matrix} \right)$

For which of the values of  $a \in \left( -5, -4, -3,-2,-1,0,1,2,3,4,5 \right)$ this is true? What is the value of $c$ then?

Tip: Make a loop that prints out the inverse of $A$ for each value of $a$. Then, check which value of $a$ gives the needed inverse matrix and find from there the value for $c$.

In [ ]:
# Solution for problem 10
