In [1]:
name = ""
student_number = "" # Write your student number here
date_returned = "23.2"

# Lab 6. Matrices
Hardware 1 - Mathematics Python Labs<br>
Information and Communication Technology<br>


## Setup

Read necessary libraries and functions.

In [14]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import det, inv, solve

---
## Problem 1

In [6]:
# Initialize random number generator
rng = np.random.default_rng(seed=2)

# Generate two random matrices
A = rng.integers(low=-10, high=10, size=(3, 3))
B = np.linalg.inv(A)

# Print them
print('A = \n', A)
print('B = \n', B)

A = 
 [[ 6 -5 -8]
 [-5 -2  6]
 [-1 -9 -4]]
B = 
 [[ 0.39240506  0.32911392 -0.29113924]
 [-0.16455696 -0.20253165  0.02531646]
 [ 0.2721519   0.37341772 -0.23417722]]


Calculate the matrix operations $C = AB$ and $D = BA$. What do you observe?

In [13]:
# My code to solve C = AB
C = A @ B
print (C)

[[ 1.00000000e+00  0.00000000e+00  2.22044605e-16]
 [ 1.11022302e-16  1.00000000e+00  2.77555756e-16]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00]]


In [12]:
# My code to solve D = BA
D = B @ A
print (D)

[[ 1.00000000e+00 -2.77555756e-16  2.22044605e-16]
 [ 1.73472348e-16  1.00000000e+00  2.77555756e-17]
 [-1.94289029e-16 -1.94289029e-16  1.00000000e+00]]


In [8]:
# My observation about the results


[[ 1.00000000e+00  0.00000000e+00  2.22044605e-16]
 [ 1.11022302e-16  1.00000000e+00  2.77555756e-16]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00]]


NameError: name 'C2' is not defined

---
## Problem 2

In [ ]:
# Initialize random number generator
rng = np.random.default_rng(seed=2)

# Generate two random matrices
A = rng.integers(low=-10, high=10, size=(2, 2))
b = rng.integers(low=-10, high=10, size=(2, 1))

# Print them
print('A = \n', A)
print('b = \n', b)

Write your own code that solves these equations: (**manually yourself, not using any linear algebra functions from numpy**) 

\begin{align*} 
a_{11} x + a_{12}y &=  b_1 \\ 
a_{21} x + a_{22} y &= b_2
\end{align*}


Then, check your answer using `numpy.linalg.solve()`.

In [8]:
# My code to solve the linear equations for x and y

In [ ]:
# Check with numpy.linalg.solve


---
## Problem 3
Solve the following equations using numpy linear algebra operations

$$ Ax = b $$

In [16]:
# Initialize random number generator
rng = np.random.default_rng(seed=2)

# Generate two random matrices
A = rng.integers(low=-100, high=100, size=(5, 5))
b = rng.integers(low=-100, high=100, size=(5, 1))

# Print them
print('A = \n', A)
print('b = \n', b)

A = 
 [[ 67 -48 -79 -41 -18]
 [ 62 -10 -82 -34  20]
 [ 62  45  98 -63  76]
 [-89  11 -46 -60  31]
 [-39  12 -48 -70  49]]
b = 
 [[-14]
 [ 35]
 [ 33]
 [ 89]
 [-16]]


In [17]:
# My solution for problem 3
x = solve(A, b)


---
## Problem 4
If $a_n = n$, find **the determinant** of the matrix
$A = \left( \begin{matrix} 
a_1 & a_2 & a_3 & a_4 & a_5 \\
a_5 & a_1 & a_2 & a_3 & a_4 \\
a_4 & a_5 & a_1 & a_2 & a_3 \\
a_3 & a_4 & a_5 & a_1 & a_2 \\
a_2 & a_3 & a_4 & a_5 & a_1 \\
\end{matrix} \right)$. Give the final answer in integers.

In [ ]:
# Solution for problem 4


---
## Problem 5
If $ A(a, x) = \left( \begin{matrix}
a + x & a - x & a - x \\
a - x & a + x & a - x \\
a - x & a - x & a + x
\end{matrix} \right)$ and $a = 3.0$, find $x > 0$, so that $det(A(a, x)) = 0$. 

How are $a$ and $x$ related? When you have found the relationship, try another value for $a$.

Tip: Make a code that 
- uses linearly spaced values for $x \in [0, 10]$, for example. Use `numpy.linspace`.
- calculates the $f(x) = det(A(a, x))$ for all values of $x$ and then 
- makes a graphical plot of $f(x)$ versus $x$. 
- Finally, from the graph, find when $f(x) = 0$.

In [ ]:
# Solution for problem 5




In [14]:
# My studies on the relationship between a and x
